import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/programmer.png" sizes="any" />
      </head>
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
